# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_99Zxu6M7Cynj4w6e22HJM9vAlErI8Cj
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from sympy import inverse_laplace_transform

sp.init_printing(use_unicode=False, wrap_line=False)

t, s = sp.symbols('t s', real=True)
I0, Ip0 = 12.0, 0.0
Is = sp.symbols('Is')

lhs = (s**2*Is - s*I0 - Ip0) + 1.4*(s*Is - I0) + 4*Is
rhs = 80 * s / (s**2 + 4)

Is_sol = sp.simplify(sp.solve(sp.Eq(lhs, rhs), Is)[0])

print("Laplace-domain solution I(s) =")
sp.pprint(sp.together(Is_sol))
print()

I_t = inverse_laplace_transform(Is_sol, s, t)
I_t = sp.simplify(sp.re(I_t))

print("Time-domain solution I(t) =")
sp.pprint(I_t)
print()

t_num = np.linspace(0, 15, 1000)
I_num = sp.lambdify(t, I_t, 'numpy')(t_num)
F_num = 80 * np.cos(2 * t_num)

plt.figure(figsize=(10, 8))

ax1 = plt.subplot(2, 1, 1)
color1 = 'tab:blue'
ax1.plot(t_num, I_num*1000, color=color1, lw=2, label='Inventory I(t)')
ax1.set_xlabel('Time t (weeks)')
ax1.set_ylabel('Inventory (units)', color=color1)
ax1.tick_params(axis='y', labelcolor=color1)
ax1.grid(True, alpha=0.3)
ax1.set_title('Seasonal Inventory Response – Laplace Solution')

ax2 = ax1.twinx()
color2 = 'tab:red'
ax2.plot(t_num, F_num, color=color2, lw=1.8, ls='--', label='Demand 80cos(2t)')
ax2.set_ylabel('Demand (units)', color=color2)
ax2.tick_params(axis='y', labelcolor=color2)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper right')

plt.subplot(2, 1, 2)
plt.plot(t_num, F_num, 'r-', lw=2, label='Demand F(t)')
plt.xlabel('Time t (weeks)')
plt.ylabel('Demand (units)')
plt.title('Seasonal Demand Profile')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

