# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZTCIQokHu1XNwBF7vaeRJs44FIpyRqJ
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from sympy import inverse_laplace_transform

sp.init_printing(use_unicode=False, wrap_line=False)

t, s = sp.symbols('t s', real=True)
Y0, Yp0 = 0.0, 0.0

Ys = sp.symbols('Ys')

lhs = (s**2*Ys - s*Y0 - Yp0) + 1.2*(s*Ys - Y0) + 3*Ys

rhs = 10 * (1/s - sp.exp(-5*s)/s)

Ys_sol = sp.solve(sp.Eq(lhs, rhs), Ys)[0]
Ys_sol = sp.simplify(Ys_sol)

print("Laplace-domain solution Y(s) =")
print(Ys_sol)
print()

Y_t = inverse_laplace_transform(Ys_sol, s, t)
Y_t = sp.simplify(sp.re(Y_t))

print("Time-domain solution Y(t) =")
print(sp.nsimplify(Y_t))
print()

t_num = np.linspace(0, 25, 1200)
Y_num = sp.lambdify(t, Y_t, 'numpy')(t_num)

F_num = np.where((t_num >= 0) & (t_num < 5), 10.0, 0.0)

plt.figure(figsize=(10, 8))

plt.subplot(2, 1, 1)
plt.plot(t_num, Y_num, 'b-', lw=2, label='Output gap Y(t)')
plt.axhline(0, color='gray', ls='--', lw=1)
plt.xlabel('Time t (years)')
plt.ylabel('Y(t) (percent of potential GDP)')
plt.title('Output Response to Temporary Fiscal Stimulus – Laplace Solution')
plt.grid(True, alpha=0.3)
plt.legend()

plt.subplot(2, 1, 2)
plt.step(t_num, F_num, where='post', color='r', lw=2, label='Fiscal stimulus F(t)')
plt.xlabel('Time t (years)')
plt.ylabel('Policy intensity')
plt.title('Temporary Stimulus Profile')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()